#!/usr/bin/env ruby
#
base = Photo.where('shot_at > ?',2.weeks.ago)

dupes = base.group(:file).having('count(file) > 1')
dupes.each do |dupe|
  all = base.where(file: dupe)
  real = all.where('md5 is not null').first
  if not real
    real = all.first
  end
  puts "DELETE: "
  puts all.where('id != ?', real.id).to_sql

  real.save
end
