#!/usr/bin/env ruby
#
base = Photo.where('shot_at > ?',2.months.ago)

dupes = base.group(:file).having('count(file) > 1').count
dupes.each do |dupe,counts|
  puts "#{dupe} -> #{counts - 1} zuviel"
  all = base.where(file: dupe)
  real = all.where('md5 is not null').first
  if not real
    real = all.first
  end
  delete =  all.where('id != ?', real.id)
  delete.delete_all
  real.save
end
